# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Project.create(univ: '고려대(세종)', date:11, lineup: '마마무')
Project.create(univ: '고려대(세종)', date:11, lineup: '베이식')
Project.create(univ: '고려대(세종)', date:12, lineup: '긱스(Geeks)')
Project.create(univ: '고려대(세종)', date:12, lineup: '한해')
Project.create(univ: '고려대(세종)', date:12, lineup: '인크레더블')
Project.create(univ: '대구가톨릭대', date:24, lineup: ' ')
Project.create(univ: '대구가톨릭대', date:25, lineup: '홍진영')
Project.create(univ: '대구가톨릭대', date:26, lineup: '도끼')
Project.create(univ: '대구가톨릭대', date:26, lineup: '더콰이엇')
Project.create(univ: '대전대', date:25, lineup: ' ')
Project.create(univ: '대전대', date:26, lineup: ' ')
Project.create(univ: '대전대', date:27, lineup: ' ')
Project.create(univ: '선문대', date:11, lineup: '밤비노')
Project.create(univ: '선문대', date:12, lineup: '긱스(Geeks)')
Project.create(univ: '선문대', date:12, lineup: 'DJ DOC')
Project.create(univ: '선문대', date:13, lineup: ' ')
Project.create(univ: '영남대', date:18, lineup: '이디오테잎')
Project.create(univ: '영남대', date:18, lineup: '크러쉬')
Project.create(univ: '영남대', date:18, lineup: '다이나믹듀오')
Project.create(univ: '영남대', date:19, lineup: '크라잉넛')
Project.create(univ: '영남대', date:19, lineup: '오일밴드')
Project.create(univ: '영남대', date:19, lineup: '장기하와 얼굴들')
Project.create(univ: '영남대', date:20, lineup: '에릭남')
Project.create(univ: '영남대', date:20, lineup: '홀릭')
Project.create(univ: '영남대', date:20, lineup: '싸이')
Project.create(univ: '한국해양대', date:11, lineup: '천재노창')
Project.create(univ: '한국해양대', date:11, lineup: '기리보이')
Project.create(univ: '한국해양대', date:12, lineup: ' ')
Project.create(univ: '한국해양대', date:13, lineup: '씨크릿')
Project.create(univ: '한세대', date:10, lineup: '마마무')
Project.create(univ: '한세대', date:11, lineup: '쿠마')
Project.create(univ: '한세대', date:11, lineup: '도끼')
Project.create(univ: '한세대', date:11, lineup: '더콰이엇')
Project.create(univ: '경북대', date:18, lineup: ' ')
Project.create(univ: '경북대', date:19, lineup: ' ')
Project.create(univ: '경북대', date:20, lineup: 'DJDOC')
Project.create(univ: '경북대', date:20, lineup: '에일리')
Project.create(univ: '동국대', date:26, lineup: '장기하와얼굴들')
Project.create(univ: '동국대', date:27, lineup: '나인뮤지스')
Project.create(univ: '동국대', date:26, lineup: '매드클라운')
Project.create(univ: '부경대', date:16, lineup: '트와이스')
Project.create(univ: '부경대', date:17, lineup: '소심한 오빠들')
Project.create(univ: '부경대', date:17, lineup: '벤')
Project.create(univ: '부경대', date:18, lineup: '산이(San E)')
Project.create(univ: '부산대', date:19, lineup: '다이나믹듀오')
Project.create(univ: '부산대', date:19, lineup: '산이(San E)')
Project.create(univ: '부산대', date:19, lineup: '매드클라운')
Project.create(univ: '상명대', date:20, lineup: '지하가요제')
Project.create(univ: '상명대', date:20, lineup: '소리마을')
Project.create(univ: '상명대', date:20, lineup: '토네이도')
Project.create(univ: '상명대', date:20, lineup: 'Groovin187')
Project.create(univ: '상명대', date:20, lineup: 'MENAP-CREW')
Project.create(univ: '상명대', date:20, lineup: '레이샤')
Project.create(univ: '상명대', date:20, lineup: '도끼')
Project.create(univ: '상명대', date:20, lineup: '더콰이엇')
Project.create(univ: '상명대', date:20, lineup: '레인보우')
Project.create(univ: '상명대', date:20, lineup: 'GreenPlayer')
Project.create(univ: '상명대', date:20, lineup: 'Done X 300(V Jing)')
Project.create(univ: '상명대', date:20, lineup: 'G-PARK')
Project.create(univ: '상명대', date:20, lineup: 'DJ BARYONYX')
Project.create(univ: '연세대', date:27, lineup: '에일리')
Project.create(univ: '연세대', date:27, lineup: 'IOI (아이오아이)')
Project.create(univ: '연세대', date:27, lineup: '다이나믹듀오')
Project.create(univ: '연세대', date:27, lineup: '하동균')
Project.create(univ: '연세대', date:27, lineup: '스윗소로우')
Project.create(univ: '연세대', date:27, lineup: '알리')
Project.create(univ: '연세대', date:27, lineup: '포미닛')
Project.create(univ: '연세대', date:27, lineup: '백아연')
Project.create(univ: '연세대', date:27, lineup: '비투비')
Project.create(univ: '연세대', date:28, lineup: '김건모')
Project.create(univ: '연세대', date:28, lineup: '쿨')
Project.create(univ: '연세대', date:28, lineup: '백지영')
Project.create(univ: '연세대', date:28, lineup: '지누션')
Project.create(univ: '연세대', date:28, lineup: '거미')
Project.create(univ: '연세대', date:28, lineup: '윤수일')
Project.create(univ: '연세대', date:28, lineup: '소찬휘')
Project.create(univ: '연세대', date:28, lineup: '송소희')
Project.create(univ: '연세대', date:28, lineup: '에릭남')
Project.create(univ: '연세대', date:28, lineup: '놀자')
Project.create(univ: '추계예술대', date:11, lineup: '로맨틱펀치')
Project.create(univ: '추계예술대', date:12, lineup: ' ')
Project.create(univ: '추계예술대', date:13, lineup: '긱스(Geeks)')
Project.create(univ: '홍익대(세종)', date:10, lineup: '마마무')
Project.create(univ: '홍익대(세종)', date:11, lineup: 'V.O.S')
Project.create(univ: '경희대(국제)', date:25, lineup: '마마무')
Project.create(univ: '경희대(국제)', date:26, lineup: 'DJ DOC')
Project.create(univ: '경희대(국제)', date:26, lineup: '에릭남')
Project.create(univ: '경희대(국제)', date:26, lineup: '여자친구')
Project.create(univ: '신한대', date:18, lineup: '에릭남')
Project.create(univ: '신한대', date:19, lineup: '싸이')
Project.create(univ: '신한대', date:19, lineup: '레이샤')
Project.create(univ: '명지대(서울)', date:17, lineup: '홍진영')
Project.create(univ: '명지대(서울)', date:17, lineup: '그레이')
Project.create(univ: '명지대(서울)', date:17, lineup: '사이먼디')
Project.create(univ: '명지대(서울)', date:18, lineup: '아놀드홍')
Project.create(univ: '명지대(서울)', date:18, lineup: '소심한오빠들')
Project.create(univ: '명지대(서울)', date:18, lineup: '레드벨벳')
Project.create(univ: '명지대(서울)', date:19, lineup: '배드키즈')
Project.create(univ: '명지대(용인)', date:11, lineup: '벤')
Project.create(univ: '명지대(용인)', date:11, lineup: '마마무')
Project.create(univ: '명지대(용인)', date:12, lineup: '산이(San E)')
Project.create(univ: '명지대(용인)', date:12, lineup: '도끼')
Project.create(univ: '명지대(용인)', date:12, lineup: '더콰이엇')
Project.create(univ: '배재대', date:18, lineup: '어반자카파')
Project.create(univ: '배재대', date:18, lineup: '레인보우')
Project.create(univ: '배재대', date:19, lineup: '바이브')
Project.create(univ: '배재대', date:20, lineup: '비와이(BewhY)')
Project.create(univ: '배재대', date:20, lineup: '사이먼디')
Project.create(univ: '한국과학기술원', date:24, lineup: '여자친구')
Project.create(univ: '한국과학기술원', date:25, lineup: '민경훈')
Project.create(univ: '한국과학기술원', date:25, lineup: '벤')
Project.create(univ: '한국과학기술원', date:26, lineup: '트와이스')
Project.create(univ: '홍익대', date:18, lineup: '홍진영')
Project.create(univ: '홍익대', date:18, lineup: '나인뮤지스')
Project.create(univ: '홍익대', date:18, lineup: '장기하와 얼굴들')
Project.create(univ: '홍익대', date:19, lineup: '케이코닉')
Project.create(univ: '홍익대', date:19, lineup: '마틸다')
Project.create(univ: '홍익대', date:19, lineup: '유니콘')
Project.create(univ: '홍익대', date:19, lineup: '밤비노')
Project.create(univ: '홍익대', date:19, lineup: '기리보이')
Project.create(univ: '홍익대', date:19, lineup: '싸이')
Project.create(univ: '홍익대', date:20, lineup: '혁오')
Project.create(univ: '홍익대', date:20, lineup: '에디킴')
Project.create(univ: '홍익대', date:20, lineup: '빈지노')
Project.create(univ: '홍익대', date:20, lineup: '로꼬')
Project.create(univ: '홍익대', date:20, lineup: '그레이')
Project.create(univ: '홍익대', date:20, lineup: 'DJ MAXIMITE')
Project.create(univ: '홍익대', date:20, lineup: 'DJ Juncoco')
Project.create(univ: '인천대', date:16, lineup: '피타입')
Project.create(univ: '인천대', date:17, lineup: '신용재')
Project.create(univ: '인천대', date:18, lineup: '윤하')
Project.create(univ: '인천대', date:18, lineup: '빈지노')
Project.create(univ: '인천대', date:18, lineup: '싸이')
Project.create(univ: '인천대', date:19, lineup: '홍대광')
Project.create(univ: '경상대', date:9, lineup: '버벌진트')
Project.create(univ: '경상대', date:11, lineup: '가비엔제이')
Project.create(univ: '경상대', date:12, lineup: '써니힐')
Project.create(univ: '이화여대', date:19, lineup: '에릭남')
Project.create(univ: '대구한의대', date:12, lineup: '홀릭')
Project.create(univ: '가톨릭대', date:21, lineup: ' ')
Project.create(univ: '가톨릭대', date:22, lineup: ' ')
Project.create(univ: '강릉원주대', date:25, lineup: '베이식(Basick)')
Project.create(univ: '강릉원주대', date:25, lineup: '십센치(10cm)')
Project.create(univ: '강릉원주대', date:26, lineup: ' ')
Project.create(univ: '경기대(서울)', date:17, lineup: ' ')
Project.create(univ: '경기대(서울)', date:18, lineup: ' ')
Project.create(univ: '경기대(서울)', date:19, lineup: ' ')
Project.create(univ: '계명대', date:10, lineup: 'SG워너비')
Project.create(univ: '계명대', date:11, lineup: ' ')
Project.create(univ: '계명대', date:12, lineup: '피에스타(FIESTAR)')
Project.create(univ: '국민대', date:17, lineup: ' ')
Project.create(univ: '국민대', date:18, lineup: ' ')
Project.create(univ: '국민대', date:19, lineup: ' ')
Project.create(univ: '국민대', date:20, lineup: ' ')
Project.create(univ: '금오공과대', date:25, lineup: '블랙넛')
Project.create(univ: '금오공과대', date:26, lineup: '벤')
Project.create(univ: '금오공과대', date:27, lineup: '싸이')
Project.create(univ: '남서울대', date:17, lineup: '여자친구')
Project.create(univ: '남서울대', date:17, lineup: 'IOI (아이오아이)')
Project.create(univ: '남서울대', date:17, lineup: '바스코')
Project.create(univ: '남서울대', date:17, lineup: '기리보이')
Project.create(univ: '남서울대', date:17, lineup: '천재노창')
Project.create(univ: '남서울대', date:18, lineup: '울랄라세션')
Project.create(univ: '남서울대', date:18, lineup: '러블리즈')
Project.create(univ: '남서울대', date:18, lineup: '더블비')
Project.create(univ: '동양대', date:17, lineup: ' ')
Project.create(univ: '동양대', date:18, lineup: ' ')
Project.create(univ: '동양대', date:19, lineup: ' ')
Project.create(univ: '서강대', date:17, lineup: ' ')
Project.create(univ: '서강대', date:18, lineup: ' ')
Project.create(univ: '서강대', date:19, lineup: ' ')
Project.create(univ: '서강대', date:20, lineup: '레인보우')
Project.create(univ: '서강대', date:20, lineup: '버즈')
Project.create(univ: '서강대', date:20, lineup: '다이나믹듀오')
Project.create(univ: '서강대', date:21, lineup: ' ')
Project.create(univ: '서울여대', date:18, lineup: ' ')
Project.create(univ: '서울여대', date:19, lineup: '딕펑스')
Project.create(univ: '서울여대', date:20, lineup: '매드크라운')
Project.create(univ: '서울여대', date:20, lineup: '참깨와 솜사탕')
Project.create(univ: '연세대(원주)', date:23, lineup: ' ')
Project.create(univ: '연세대(원주)', date:24, lineup: ' ')
Project.create(univ: '연세대(원주)', date:25, lineup: ' ')
Project.create(univ: '연세대(원주)', date:26, lineup: ' ')
Project.create(univ: '인제대', date:18, lineup: ' ')
Project.create(univ: '인제대', date:19, lineup: ' ')
Project.create(univ: '인제대', date:20, lineup: ' ')
Project.create(univ: '전북대', date:25, lineup: ' ')
Project.create(univ: '전북대', date:26, lineup: ' ')
Project.create(univ: '전북대', date:27, lineup: ' ')
Project.create(univ: '제주대', date:24, lineup: '블루미')
Project.create(univ: '제주대', date:24, lineup: '십센치(10cm)')
Project.create(univ: '제주대', date:24, lineup: '벤')
Project.create(univ: '제주대', date:25, lineup: ' ')
Project.create(univ: '제주대', date:26, lineup: ' ')
Project.create(univ: '중앙대', date:25, lineup: ' ')
Project.create(univ: '중앙대', date:26, lineup: ' ')
Project.create(univ: '중앙대', date:27, lineup: '트와이스')
Project.create(univ: '중앙대', date:27, lineup: '버즈')
Project.create(univ: '추계예술대', date:11, lineup: '로맨틱펀치')
Project.create(univ: '추계예술대', date:12, lineup: ' ')
Project.create(univ: '추계예술대', date:13, lineup: '긱스(Geeks)')
Project.create(univ: '한국기술교대', date:10, lineup: ' ')
Project.create(univ: '한국기술교대', date:11, lineup: ' ')
Project.create(univ: '한국기술교대', date:12, lineup: '산이(San E)')
Project.create(univ: '한국기술교대', date:12, lineup: '키썸(kisum)')
Project.create(univ: '한국외대', date:23, lineup: ' ')
Project.create(univ: '한국외대', date:24, lineup: ' ')
Project.create(univ: '한국외대(용인)', date:24, lineup: ' ')
Project.create(univ: '한국외대(용인)', date:25, lineup: ' ')
Project.create(univ: '한국외대(용인)', date:26, lineup: ' ')
Project.create(univ: '한동대', date:11, lineup: ' ')
Project.create(univ: '한동대', date:12, lineup: ' ')
Project.create(univ: '한동대', date:13, lineup: ' ')
Project.create(univ: '한서대', date:24, lineup: '싸이')
Project.create(univ: '한서대', date:25, lineup: ' ')
Project.create(univ: '단국대(죽전)', date:18, lineup: '옥상달빛')
Project.create(univ: '단국대(죽전)', date:18, lineup: '로맨틱펀치')
Project.create(univ: '단국대(죽전)', date:18, lineup: '십센치(10cm)')
Project.create(univ: '단국대(죽전)', date:18, lineup: '박보람')
Project.create(univ: '단국대(죽전)', date:19, lineup: '자메즈')
Project.create(univ: '단국대(죽전)', date:19, lineup: '크라이베이비')
Project.create(univ: '단국대(죽전)', date:19, lineup: '긱스(Geeks)')
Project.create(univ: '단국대(죽전)', date:19, lineup: '홍대광')
Project.create(univ: '단국대(죽전)', date:20, lineup: '송소희')
Project.create(univ: '단국대(죽전)', date:20, lineup: '딘')
Project.create(univ: '단국대(죽전)', date:20, lineup: 'EXID')
Project.create(univ: '단국대(죽전)', date:20, lineup: '에픽하이')
Project.create(univ: '한양대(ERICA)', date:24, lineup: '전용준')
Project.create(univ: '한양대(ERICA)', date:24, lineup: '클템')
Project.create(univ: '한양대(ERICA)', date:24, lineup: '거미')
Project.create(univ: '한양대(ERICA)', date:25, lineup: '딘')
Project.create(univ: '한양대(ERICA)', date:25, lineup: '에픽하이')
Project.create(univ: '한양대(ERICA)', date:26, lineup: '싸이')
Project.create(univ: '아주대', date:25, lineup: '트와이스')
Project.create(univ: '아주대', date:25, lineup: '싸이')
Project.create(univ: '아주대', date:26, lineup: '스텔라')
Project.create(univ: '아주대', date:27, lineup: '버벌진트')
Project.create(univ: '아주대', date:27, lineup: '자이언티')
Project.create(univ: '아주대', date:27, lineup: '타이거jk')
Project.create(univ: '아주대', date:27, lineup: '윤미래')
Project.create(univ: '서경대', date:11, lineup: ' ')
Project.create(univ: '서경대', date:12, lineup: '트와이스')
Project.create(univ: '서경대', date:13, lineup: '씨스타')
Project.create(univ: '서경대', date:13, lineup: '버벌진트')
Project.create(univ: '서경대', date:13, lineup: '기리보이')
Project.create(univ: '서경대', date:13, lineup: '천재노창')
Project.create(univ: '덕성여대', date:25, lineup: ' ')
Project.create(univ: '덕성여대', date:26, lineup: '에픽하이')
Project.create(univ: '덕성여대', date:27, lineup: '에릭')
Project.create(univ: '동의대', date:18, lineup: '자이언티')
Project.create(univ: '동의대', date:19, lineup: 'SG워너비')
Project.create(univ: '동의대', date:19, lineup: '온앤온')
Project.create(univ: '동의대', date:19, lineup: '고온')
Project.create(univ: '동의대', date:20, lineup: '에이핑크(apink)')
Project.create(univ: '청주대 ', date:24, lineup: ' ')
Project.create(univ: '청주대 ', date:25, lineup: '싸이')
Project.create(univ: '청주대 ', date:25, lineup: '손승연')
Project.create(univ: '청주대 ', date:26, lineup: ' ')
Project.create(univ: '평택대', date:11, lineup: '이정')
Project.create(univ: '평택대', date:12, lineup: '마마무')
Project.create(univ: '건국대', date:11, lineup: '길구봉구')
Project.create(univ: '건국대', date:11, lineup: '싸이')
Project.create(univ: '건국대', date:12, lineup: '긱스(Geeks)')
Project.create(univ: '건국대', date:12, lineup: '마마무')
Project.create(univ: '인하대', date:18, lineup: '에픽하이')
Project.create(univ: '인하대', date:18, lineup: '예지')
Project.create(univ: '인하대', date:19, lineup: '트와이스')
Project.create(univ: '한양대', date:24, lineup: '자이언티')
Project.create(univ: '한양대', date:25, lineup: '윤도현밴드 (YB)')
Project.create(univ: '한양대', date:26, lineup: ' ')
Project.create(univ: '한양대', date:27, lineup: '레드벨벳')
Project.create(univ: '성균관대', date:17, lineup: '장미여관')
Project.create(univ: '성균관대', date:17, lineup: '로꼬')
Project.create(univ: '성균관대', date:17, lineup: '박재범')
Project.create(univ: '성균관대', date:17, lineup: '윤도현밴드 (YB)')
Project.create(univ: '성균관대', date:17, lineup: 'DJ 맥시마이트')
Project.create(univ: '성균관대', date:17, lineup: 'DJ Juncoco')
Project.create(univ: '성균관대', date:18, lineup: '긱스(Geeks)')
Project.create(univ: '성균관대', date:18, lineup: 'IOI (아이오아이)')
Project.create(univ: '성균관대', date:18, lineup: '휘성')
Project.create(univ: '성균관대', date:18, lineup: '거미')
Project.create(univ: '성균관대', date:18, lineup: '에일리')
Project.create(univ: '성균관대', date:19, lineup: '기리보이')
Project.create(univ: '성균관대', date:19, lineup: '바스코')
Project.create(univ: '성균관대', date:19, lineup: '빈지노')
Project.create(univ: '성균관대', date:19, lineup: '도끼')
Project.create(univ: '성균관대', date:19, lineup: '더콰이엇')
Project.create(univ: '성균관대', date:19, lineup: '타이거JK')
Project.create(univ: '성균관대', date:19, lineup: '윤미래')
Project.create(univ: '성균관대', date:19, lineup: 'BIZZY')
Project.create(univ: '성균관대', date:19, lineup: 'DJ KOO')
Project.create(univ: '성균관대', date:19, lineup: '김신영')
Project.create(univ: '세종대', date:10, lineup: '10cm (십센치)')
Project.create(univ: '세종대', date:11, lineup: '거미')
Project.create(univ: '세종대', date:11, lineup: '나인뮤지스')
Project.create(univ: '세종대', date:11, lineup: '천단비')
Project.create(univ: '세종대', date:11, lineup: '케빈오')
Project.create(univ: '세종대', date:12, lineup: 'IOI (아이오아이)')
Project.create(univ: '세종대', date:12, lineup: '에픽하이')
Project.create(univ: '경성대', date:10, lineup: '싸이')
Project.create(univ: '경성대', date:11, lineup: '장범준')
Project.create(univ: '경성대', date:12, lineup: '버벌진트')
Project.create(univ: '경성대', date:12, lineup: 'EXID')
Project.create(univ: '경성대', date:12, lineup: '다이나믹듀오')
Project.create(univ: '성균관대(자연과학)', date:11, lineup: '싸이')
Project.create(univ: '성균관대(자연과학)', date:11, lineup: '마마무')
Project.create(univ: '성균관대(자연과학)', date:11, lineup: 'DJ ALPHA (DJ 알파)')
Project.create(univ: '성균관대(자연과학)', date:11, lineup: 'DJ CONAN (DJ 코난)')
Project.create(univ: '성균관대(자연과학)', date:12, lineup: '크라잉넛')
Project.create(univ: '성균관대(자연과학)', date:12, lineup: '어반자카파')
Project.create(univ: '성균관대(자연과학)', date:12, lineup: '몽니')
Project.create(univ: '성균관대(자연과학)', date:12, lineup: '데이브레이크')
Project.create(univ: '성균관대(자연과학)', date:12, lineup: '어쿠스틱콜라보')
Project.create(univ: '성균관대(자연과학)', date:12, lineup: '솔루션스')
Project.create(univ: '성균관대(자연과학)', date:12, lineup: '랄라스윗')
Project.create(univ: '성균관대(자연과학)', date:12, lineup: '고고보이즈')
Project.create(univ: '성균관대(자연과학)', date:13, lineup: '에픽하이')
Project.create(univ: '성균관대(자연과학)', date:13, lineup: '로꼬')
Project.create(univ: '성균관대(자연과학)', date:13, lineup: '그레이')
Project.create(univ: '성균관대(자연과학)', date:13, lineup: 'DJ 바가지')
Project.create(univ: '상명대(천안)', date:10, lineup: '산이(San E)')
Project.create(univ: '상명대(천안)', date:10, lineup: '홍진영')
Project.create(univ: '상명대(천안)', date:11, lineup: 'Loxx Punkman')
Project.create(univ: '상명대(천안)', date:11, lineup: '빈지노')
Project.create(univ: '상명대(천안)', date:11, lineup: '그레이스')
Project.create(univ: '상명대(천안)', date:11, lineup: '버벌진트')
Project.create(univ: '상명대(천안)', date:12, lineup: '베티엘')
Project.create(univ: '상명대(천안)', date:12, lineup: '김보경')
Project.create(univ: '상명대(천안)', date:12, lineup: '어쿠스틱콜라보')
Project.create(univ: '서울시립대', date:18, lineup: '박보람')
Project.create(univ: '서울시립대', date:19, lineup: '로꼬')
Project.create(univ: '서울시립대', date:19, lineup: '그레이')
Project.create(univ: '서울시립대', date:19, lineup: '크러쉬')
Project.create(univ: '서울시립대', date:20, lineup: '도끼')
Project.create(univ: '서울시립대', date:20, lineup: '더콰이엇')
Project.create(univ: '서울시립대', date:20, lineup: '러블리즈')
Project.create(univ: '원광대', date:10, lineup: '먼데이키즈')
Project.create(univ: '원광대', date:11, lineup: '씨스타')
Project.create(univ: '원광대', date:11, lineup: '10cm (십센치)')
Project.create(univ: '원광대', date:11, lineup: '에일리')
Project.create(univ: '원광대', date:12, lineup: '매드클라운')
Project.create(univ: '한남대', date:10, lineup: '양동근')
Project.create(univ: '한남대', date:10, lineup: '전우람')
Project.create(univ: '한남대', date:10, lineup: '달샤벳')
Project.create(univ: '한남대', date:10, lineup: '나비')
Project.create(univ: '한남대', date:10, lineup: '포스트맨')
Project.create(univ: '한남대', date:11, lineup: '다이나믹듀오')
Project.create(univ: '한남대', date:12, lineup: 'DJ.S-PSYCHO')
Project.create(univ: '한남대', date:12, lineup: '블랙퀸')
Project.create(univ: '연세대', date:21, lineup: '트와이스')
Project.create(univ: '연세대', date:21, lineup: '성시경')
Project.create(univ: '연세대', date:21, lineup: '에픽하이')
Project.create(univ: '연세대', date:21, lineup: '윤도현밴드 (YB)')
Project.create(univ: '연세대', date:21, lineup: '블락비')
Project.create(univ: '연암공과대', date:12, lineup: '오마이걸')
Project.create(univ: '경민대', date:26, lineup: '오마이걸')
Project.create(univ: '동국대', date:26, lineup: '오마이걸')
Project.create(univ: '한국폴리텍대', date:19, lineup: '오마이걸')
Project.create(univ: '한림대', date:19, lineup: '오마이걸')
Project.create(univ: '한밭대', date:19, lineup: '오마이걸')
Project.create(univ: '부산과기대', date:13, lineup: '오마이걸')
Project.create(univ: '서울대', date:17, lineup: '오마이걸')
Project.create(univ: '강원대', date:24, lineup: '오마이걸')
Project.create(univ: '숙명여대', date:26, lineup: '로이킴')
Project.create(univ: '숙명여대', date:27, lineup: '장기하와 얼굴들')
Project.create(univ: '연세대(원주)', date:23, lineup: '소심한 오빠들')
Project.create(univ: '연세대(원주)', date:23, lineup: '투빅')
Project.create(univ: '연세대(원주)', date:23, lineup: '유승우')
Project.create(univ: '연세대(원주)', date:25, lineup: '안수민')
Project.create(univ: '연세대(원주)', date:25, lineup: '딕펑스')
Project.create(univ: '연세대(원주)', date:25, lineup: '마마무')
Project.create(univ: '연세대(원주)', date:25, lineup: '김범수')